import React from 'react';
import {
  LayoutDashboard,
  FlaskConical,
  ClipboardPen,
  LineChart,
  NotebookText,
  Settings,
  Plus,
  Trash2,
  Save,
  Activity,
  Droplet,
  AlertTriangle,
  Sparkles,
  Download,
  Snowflake,
  Flame,
  Wind,
  Factory,
  X,
  FilePenLine,
  GripVertical,
  RefreshCw,
  Calculator,
  Import,
  Calendar,
  FileText,
  HelpCircle
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Tank: FlaskConical,
  Entry: ClipboardPen,
  ClipboardPen: ClipboardPen,
  Analysis: LineChart,
  Notes: NotebookText,
  Settings: Settings,
  Plus: Plus,
  Delete: Trash2,
  Save: Save,
  Activity: Activity,
  Droplet: Droplet,
  Alert: AlertTriangle,
  AI: Sparkles,
  Download: Download,
  Cooling: Snowflake,
  Boiler: Flame,
  DeNOx: Wind,
  Factory: Factory,
  X: X,
  FilePenLine: FilePenLine,
  Trash2: Trash2,
  DragHandle: GripVertical,
  Import: Import,
  Recycle: RefreshCw,
  Calculator: Calculator,
  Calendar: Calendar,
  FileText: FileText,
  Help: HelpCircle
};
